### ISSUE TITLE
fix stylint

### ISSUE THREAD

**Issue by ahmadaidil** [volantis-technology/volantis-ui#36]
@elishaenu gw baru nambahin stylint which is code linter for styled di branch dev.

after i added, gw menemukan bbrp yg harus diperbaiki.
<img width="1066" alt="screen shot 2019-02-27 at 17 08 09" src="https://user-images.githubusercontent.com/29198930/53482778-992d8e00-3ab2-11e9-99f6-2309b10c5d4c.png">

silahkan bikin branch 'fix-styling' to solve that issue. thx.

**Comment by ahmadaidil** [comment]
@elishaenu utk err no-descending-specificity coba pindahin posisi codenya dinaikin keatas ato diturunin.

**Comment by elishaenu** [comment]
https://github.com/volantis-technology/volantis-ui/pull/42

mohon review, trimakasihh
