### ISSUE TITLE
Modal Without Padding

### ISSUE THREAD

**Issue by nadiarii** [volantis-technology/volantis-ui#38]
Enyu.. untuk modal yang sekarang tolong sediakan props padding dong. Untuk sekarang kan default padding 40px, aku butuh modal yang padding nya 0.  :D

Thanks before.

**Comment by ahmadaidil** [comment]
@elishaenu add props aja `noPadding`

**Comment by elishaenu** [comment]
https://github.com/volantis-technology/volantis-ui/pull/40

coba di review ya darisanaa. terimakasih @nadiarii @ahmadaidil

**Comment by ahmadaidil** [comment]
issue solved in v1.0.6
