### ISSUE TITLE
rename props title to label

### ISSUE THREAD

**Issue by ahmadaidil** [volantis-technology/volantis-ui#45]
rename props.title or props.name (as labeling) to props.label
e.g:
```jsx
<Input title="test" />
```
output e.g:
```ui
test:
[ input here...     ]
```
better name as props.label

fyi. @saripp @nadiarii

**Comment by elishaenu** [comment]
tanya dong : 

yang udah ada sekarang : props title dan props name
apakah yang dimaksud adalah props title diganti menjadi props label?
jika iya, apakah bukan lebih baik kalau props nya tetap title saja? 
takutnya kalau props label bisa tertukar / bingung dengan component label.

terima kasih

cc : @ahmadaidil @nadiarii @saripp

**Comment by ahmadaidil** [comment]
ada 3 pilihan:
* label
* labelName
* labelTitle

@elishaenu @nadiarii @saripp

**Comment by elishaenu** [comment]
https://github.com/volantis-technology/volantis-ui/pull/53

tolong direview yaa
terimakasih

@ahmadaidil @nadiarii @saripp

**Comment by elishaenu** [comment]
1. id sudah diganti menjadi not required
2. id langsung diisi dengan name, sehingga user tidak perlu mengisi id lagi
