### ISSUE TITLE
use rem func to convert px to rem

### ISSUE THREAD

**Issue by ahmadaidil** [volantis-technology/volantis-ui#46]
example use:
```js
import styled from 'styled'
import rem from 'polished/lib/helpers/rem'

const Wrapper = styled.div`
  padding: ${rem('10px')}
`
```

pengecualian utk
```css
border: 1px solid #ffd77b;
```
tebal border lebih dari 1px? pake rem func.

note:
<img width="354" alt="screen shot 2019-02-28 at 02 20 54" src="https://user-images.githubusercontent.com/29198930/53516760-9d33cd00-3aff-11e9-9eb1-7e9a3aaf5a1e.png">
jangan pake destructing import ya, concern dist bundle size nya nanti.
karena dia sifatnya libs, which is ga semua func2 dari dia kita pake.

import from 'polished' berarti waktu bundling, semua func2 polished ke build.
tp kalo 'polished/lib/bla/bla', cuman func itu doang ke bundling.

**Comment by elishaenu** [comment]
https://github.com/volantis-technology/volantis-ui/pull/58

mohon review @ahmadaidil terima kasih

**Comment by ahmadaidil** [comment]
@elishaenu merged
