### ISSUE TITLE
input and select there is no disabled props

### ISSUE THREAD

**Issue by ahmadaidil** [volantis-technology/volantis-ui#47]
@elishaenu seperti kita tahu, yang berhubungan dengan form component harus ada disabled props

**Comment by elishaenu** [comment]
https://github.com/volantis-technology/volantis-ui/pull/52

review dari PR ini, terimakasih

**Comment by elishaenu** [comment]
1. id sudah diganti menjadi not required
2. id langsung diisi dengan name, sehingga user tidak perlu mengisi id lagi

**Comment by ahmadaidil** [comment]
#52 merged
