### ISSUE TITLE
Search Input

### ISSUE THREAD

**Issue by luthfi-volantis** [volantis-technology/volantis-ui#70]
When the search icon clicked, the input cursor should be active

**Comment by ahmadaidil** [comment]
cc: @elishaenu tolong tambahin cursor pointer sama kek visibility

**Comment by elishaenu** [comment]
https://github.com/volantis-technology/volantis-ui/pull/71

@ahmadaidil  mohon review, terimakasih
cc : @luthfi-volantis

**Comment by ahmadaidil** [comment]
@luthfi-volantis @elishaenu  udah di merged ya, tunggu v1.0.7 release.
